// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: License.proto

#ifndef PROTOBUF_License_2eproto__INCLUDED
#define PROTOBUF_License_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace license {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_License_2eproto();
void protobuf_AssignDesc_License_2eproto();
void protobuf_ShutdownFile_License_2eproto();

class License;

// ===================================================================

class License : public ::google::protobuf::Message {
 public:
  License();
  virtual ~License();
  
  License(const License& from);
  
  inline License& operator=(const License& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const License& default_instance();
  
  void Swap(License* other);
  
  // implements Message ----------------------------------------------
  
  License* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const License& from);
  void MergeFrom(const License& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 global_nodes = 1;
  inline bool has_global_nodes() const;
  inline void clear_global_nodes();
  static const int kGlobalNodesFieldNumber = 1;
  inline ::google::protobuf::int32 global_nodes() const;
  inline void set_global_nodes(::google::protobuf::int32 value);
  
  // required int32 node_sessions = 2;
  inline bool has_node_sessions() const;
  inline void clear_node_sessions();
  static const int kNodeSessionsFieldNumber = 2;
  inline ::google::protobuf::int32 node_sessions() const;
  inline void set_node_sessions(::google::protobuf::int32 value);
  
  // required int32 node_session_rate = 3;
  inline bool has_node_session_rate() const;
  inline void clear_node_session_rate();
  static const int kNodeSessionRateFieldNumber = 3;
  inline ::google::protobuf::int32 node_session_rate() const;
  inline void set_node_session_rate(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:license.License)
 private:
  inline void set_has_global_nodes();
  inline void clear_has_global_nodes();
  inline void set_has_node_sessions();
  inline void clear_has_node_sessions();
  inline void set_has_node_session_rate();
  inline void clear_has_node_session_rate();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 global_nodes_;
  ::google::protobuf::int32 node_sessions_;
  ::google::protobuf::int32 node_session_rate_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_License_2eproto();
  friend void protobuf_AssignDesc_License_2eproto();
  friend void protobuf_ShutdownFile_License_2eproto();
  
  void InitAsDefaultInstance();
  static License* default_instance_;
};
// ===================================================================


// ===================================================================

// License

// required int32 global_nodes = 1;
inline bool License::has_global_nodes() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void License::set_has_global_nodes() {
  _has_bits_[0] |= 0x00000001u;
}
inline void License::clear_has_global_nodes() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void License::clear_global_nodes() {
  global_nodes_ = 0;
  clear_has_global_nodes();
}
inline ::google::protobuf::int32 License::global_nodes() const {
  return global_nodes_;
}
inline void License::set_global_nodes(::google::protobuf::int32 value) {
  set_has_global_nodes();
  global_nodes_ = value;
}

// required int32 node_sessions = 2;
inline bool License::has_node_sessions() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void License::set_has_node_sessions() {
  _has_bits_[0] |= 0x00000002u;
}
inline void License::clear_has_node_sessions() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void License::clear_node_sessions() {
  node_sessions_ = 0;
  clear_has_node_sessions();
}
inline ::google::protobuf::int32 License::node_sessions() const {
  return node_sessions_;
}
inline void License::set_node_sessions(::google::protobuf::int32 value) {
  set_has_node_sessions();
  node_sessions_ = value;
}

// required int32 node_session_rate = 3;
inline bool License::has_node_session_rate() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void License::set_has_node_session_rate() {
  _has_bits_[0] |= 0x00000004u;
}
inline void License::clear_has_node_session_rate() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void License::clear_node_session_rate() {
  node_session_rate_ = 0;
  clear_has_node_session_rate();
}
inline ::google::protobuf::int32 License::node_session_rate() const {
  return node_session_rate_;
}
inline void License::set_node_session_rate(::google::protobuf::int32 value) {
  set_has_node_session_rate();
  node_session_rate_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace license

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_License_2eproto__INCLUDED
