all:
	g++ -std=c++0x -I /media/data/git/orchid-sw/orchid/thirdparty/protobuf/protobuf-2.4.1/include/ client.cc ../server/License.pb.cc -L=/media/data/git/orchid-sw/orchid/thirdparty/protobuf/protobuf-2.4.1/lib/ -lprotobuf -pthread -o client
